# Generated by Django 3.2.2 on 2021-05-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(choices=[('Alicja Sinicka', 'Sinicka'), ('Harlan Coben', 'Coben'), ('Remigiusz Mróz', 'Mroz'), ('Suzanne Collins', 'Collins'), ('Anna Wolf', 'Wolf')], default='Harlan Coben', max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('comment', models.CharField(max_length=250)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
